@TestJob.Api_HostAddress = http://localhost:8090

### Обработать первый предоставленный набор данных
POST {{TestJob.Api_HostAddress}}/api/process-page
Content-Type: application/json

< ../../../json_payload_1.txt

### Обработать второй предоставленный набор данных
POST {{TestJob.Api_HostAddress}}/api/process-page
Content-Type: application/json

< ../../../json_payload_2.txt
